type LiteralUnion<T extends string> = T | (string & Record<never, never>);

export const knownIconNames = [
  "ArrowRight",
  "ArrowUp",
  "ArrowUpRight",
  "ChevronDown",
  "ChevronLeft",
  "ChevronRight",
  "ChevronUp",
  "ChevronsRight",
  "Clock",
  "Diamond",
  "Dribbble",
  "Facebook",
  "Github",
  "Instagram",
  "Languages",
  "Link",
  "Linkedin",
  "Mail",
  "MailOpen",
  "MessageCircle",
  "Minus",
  "MoveLeft",
  "MoveRight",
  "Phone",
  "Pinterest",
  "Play",
  "Plus",
  "Rocket",
  "Search",
  "Send",
  "Star",
  "TriangleRight",
  "Twitter",
  "TwitterNew",
  "TwitterOld",
  "X",
  "Youtube",
] as const;

export type KnownIconName = (typeof knownIconNames)[number];
export type IconName = LiteralUnion<KnownIconName>;
